version: '3.8'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    environment:
      - DB_ENV=docker  # Set the environment variable to 'docker' for the app
      - DB_HOST=db     # Host for database connection

  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always

networks:
  app-network:
    driver: bridge