name: Bug Report [FORM]
description: File a bug report for SET08103_2024-5 Project.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["/SET08103_2024-5"]
assignees:
  - project-maintainer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please provide detailed information to help us address it effectively.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue in detail. What did you expect to happen, and what actually happened?
      placeholder: "E.g., I accessed the World Reports for continents, expected continent-wise data, but got a 404 error."
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Type of Report
      description: Which report type is impacted by this issue?
      options:
        - World Reports
        - TopN Reports - Countries
        - TopN Reports - Cities
        - City Reports
        - TopN Reports - Capital Cities
        - Population Breakdown
        - Total Population
        - Languages
        - Other
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Application Version
      description: What version of the application are you using?
      options:
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - Latest
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser(s) Used
      description: Select the browser(s) where the issue was observed.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the bug.
      placeholder: "1. Go to the index page.\n2. Click on 'TopN Reports - Cities'.\n3. Observe the issue."
    validations:
      required: true

  - type: checkboxes
    id: severity
    attributes:
      label: Severity of the Issue
      description: How severe is the impact of this issue?
      options:
        - label: Low (Minor inconvenience)
        - label: Medium (Moderate impact, workaround available)
        - label: High (Severe impact, no workaround)
        - label: Critical (Feature or application unusable)

