    @startuml
    left to right direction

    actor mem as "Data Analyst"

    rectangle Database

    rectangle "Capital System" {

        usecase UC1 as "Get all capitals in the world"
        usecase UC2 as "Get top N capitals"
        usecase UC3 as "Get all capitals in a country"
        usecase UC4 as "Print report"

        usecase UCa as "No user input provided"
        usecase UCb as "No database connection"

        mem -- UC1
        mem -- UC2
        mem -- UC3

        UC1 --- Database
        UC2 --- Database
        UC3 --- Database

        UC1 ..> UC4 : include
        UC2 ..> UC4 : include
        UC3 ..> UC4 : include

        UC2 <. UCa : extends
        UC1 <. UCb : extends

    }

    @enduml