@startuml
left to right direction
actor mem as "Org. Member"

rectangle Database

rectangle "Country System" {

        usecase UC1 as "Get all countries in the world"
        usecase UC2 as "Get top N counties in a continent"
        usecase UC3 as "Get all cities in a region"
        usecase UC4 as "Print report"

        usecase UCa as "User input invalid"
        usecase UCb as "No database connection"

        mem -- UC1
        mem -- UC2
        mem -- UC3

        UC1 --- Database
        UC2 --- Database
        UC3 --- Database

        UC1 ..> UC4 : include
        UC2 ..> UC4 : include
        UC3 ..> UC4 : include

        UC2 <.. UCa : extends
        UC1 <. UCb : extends
        UCb .> UC2 : extends
        UCb .> UC3 : extends

}

@enduml