@startuml

actor mem as "Org. Member"

rectangle Database

rectangle "Population System" {
    usecase UC1 as "Get populations
    by country"

    usecase UCa as "Print populations"

    mem - UC1
    UC1 ..> UCa : include
    UC1 - Database
}

@enduml