# GitHub Actions workflow for building and running a Java application
# Triggers on push to the repository
name: A workflow for my Hello World App
on:
  push:  # Runs the workflow when changes are pushed

jobs:
  build:  # Job for building application
    name: Hello world action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout  # Check out the code
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Includes submodules

      # Install JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

      - name: Build with Maven  # Build the application
        run: mvn package -DskipTests  # Compiles and packages the application

      - name: Run docker compose  # Run Docker Compose
        run: docker compose up --abort-on-container-exit  # Starts services and aborts on container exit
