# Name of the github workflow
name: A workflow for my Hello World App
# When the repo is pushed it will run this workflow
on: push

jobs:
  build:
  # Name of the action
    name: Hello world action
  # Specifies what vm environment it's going to run
    runs-on: ubuntu-20.04
  # List of steps to complete the workflow
    steps:
    # Checkout the code from the repo
      - name: Checkout
        uses: actions/checkout@v2
    # Set up the jdk for the vm and specify what version
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
    # Compile the project using maven running the command clean package
      - name: Compile with Maven
        run: mvn clean package
    # Builds the docker image from the dockerfile
      - name: Build Docker Image
        run: docker build -t semimage .
    # Runs the docker image to create a container
      - name: Run image
        run: docker run --name semcontainer -d semimage
    # View the logs of the running container
      - name: view logs
        run: docker logs semcontainer
